### ISSUE TITLE
dotLottie file support on native side

### ISSUE THREAD

**Issue by ranaavneet** [margelo/react-native-skottie#7]
Hi, is there a way to add dotLottie files to ios and android native side? So that we can directly pass the file name?

**Comment by hannojg** [comment]
Oh, you mean for example when you store it on android in the `res/raw` folder? Yeah, we can add support for that, sure!

**Comment by ranaavneet** [comment]
Yes, thats correct. Do you think that helps in performance, since the file doesn't go over bridge?

**Comment by hannojg** [comment]
This module uses JSI, so it's not going over the bridge. If your Lottie file is huge, there _might_ be a little performance impact on the JS Thread though for calling the JSI function with such a large string (and converting it to an jsi::string).

So, yes, when passing the native resource you avoid that one heavy call in JS. However, I'd want to first profile the impact of that function call, because it might only have a performance impact in the nanosecond range 😄 

Note to myself:
We experiment to improve performance by passing the data as an array buffer.

**Comment by hannojg** [comment]
Oh actually we already support dotLottie files on native side:

https://github.com/margelo/react-native-skottie/blob/20fdf139cb09b6731d7918b1e92d220ddd3ee3a0/package/android/src/main/java/com/skiaskottie/DotLottieReader.java#L55-L63

You should be able to just pass the name of the resource! (On android)

**Comment by ranaavneet** [comment]
Thats great, iOS would also be great
